apiVersion: v1
kind: Service
metadata:
  name: lolcat
  labels:
    app: lolcat
    tier: backend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: lolcat
    tier: backend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: lolcat
spec:
  selector:
    matchLabels:
      app: lolcat
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: lolcat
        tier: backend
    spec:
      containers:
        - name: lolcat
          image: jyee/lolcat:0.3.7
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: DD_SOCKET_PATH
              value: "/var/run/datadog"
            - name: DATADOG_SERVICE_NAME
              value: "lolcat"
            - name: DD_ANALYTICS_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
          volumeMounts:
            - name: dsdsocket
              mountPath: /var/run/datadog
          volumes:
            - hostPath:
                path: /var/run/datadog/
              name: dsdsocket
