apiVersion: v1
kind: Service
metadata:
  name: memebook
  labels:
    app: memebook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: memebook
    tier: frontend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: memebook
spec:
  selector:
    matchLabels:
      app: memebook
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: memebook
        tier: frontend
    spec:
      containers:
        - name: memebook
          image: jyee/memebook:0.3.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DD_SOCKET_PATH
              value: "/var/run/datadog"
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: DATADOG_SERVICE_NAME
              value: "memebook"
            - name: DD_ANALYTICS_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
          volumeMounts:
            - name: dsdsocket
              mountPath: /var/run/datadog
          volumes:
            - hostPath:
                path: /var/run/datadog/
              name: dsdsocket
